
apiVersion: argoproj.io/v2alpha1
apiVersion: argoproj.io/v1alpha2
apiVersion: argoproj.io/v2alphai
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook1
